[package]
name = "unlock-parachain"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.13"
hex = "0.4.3"
subxt = { version = "0.38.0" }
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
